project:
  type: website

lang: en

website:
  title: "Junker et al. (2024): Joint effects in psychology"
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - file: supplement_1.qmd
        text: Supplement 1
      - file: supplement_2.qmd
        text: Supplement 2
    tools:
      - icon: github
        href: https://github.com/FlorianPargent/joint_effects_ampps
  back-to-top-navigation: true
  bread-crumbs: true

author: 
  - name: Lukas Junker
    orcid: 0009-0005-2898-2709
    email: lukas.junker@psy.lmu.de
    affiliations:
      - LMU Munich
  - name: Ramona Schoedel
    orcid: 0000-0001-7275-0626
    affiliations:
      - Charlotte Fresenius University, Munich
      - LMU Munich
  - name: Florian Pargent
    orcid: 0000-0002-2388-553X
    affiliations:
      - LMU Munich

license: "CC BY"
csl: apa.csl

format:
  html:
    theme: [brand, styles.scss]
    code-copy: true
    toc: true
    citation:
      type: article-journal
      title: "Towards a Clearer Understanding of Causal Estimands: The Importance of Joint Effects in Longitudinal Designs with Time-Varying Treatments."
      id: "junker2024"
      container-title: "PsyArXiv"
      doi: "10.31234/osf.io/zmh5a"
      issued: 2024

execute: 
  freeze: false

